<?php

namespace AppBundle\Repository;

/**
 * cartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cartRepository extends \Doctrine\ORM\EntityRepository
{
}
